[package]
name = "dz-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core logic shared by the Dangerzone applications"

[lints]
workspace = true

[dependencies]
dirs-next = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
thiserror = { workspace = true }
unicode-general-category = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
