//! The container isolation provider.
//!
//! Corresponds to `dangerzone/isolation_provider/container.py`. It runs the
//! document-to-pixels conversion inside a disposable container started by the
//! configured container runtime.

use std::process::Stdio;

use dz_core::document::Document;

use crate::base::{terminate_process_group, ConversionProcess, ConvertError, IsolationProvider};
use crate::container_utils;
use crate::podman::cli_runner::SpawnOptions;
use crate::podman::errors::CommandError;
use crate::updater::{bypass_signature_checks, verify_local_image};

/// The container isolation provider.
pub struct Container {
    debug: bool,
}

impl Container {
    /// Creates a new container provider.
    pub fn new(debug: bool) -> Self {
        Self { debug }
    }

    /// Security options applicable to the outer Dangerzone container.
    ///
    /// See the Python docstring for the rationale behind each option. The
    /// hardened seccomp profile is generated by
    /// [`container_utils::make_seccomp_json_accessible`]. The `--userns nomap`
    /// remapping is a Podman feature and is skipped for Docker, mirroring
    /// `container_utils.get_runtime_security_args()`.
    fn get_runtime_security_args() -> Vec<String> {
        let mut security_args = vec!["--log-driver".to_string(), "none".to_string()];
        security_args.push("--security-opt".to_string());
        security_args.push("no-new-privileges".to_string());
        if container_utils::is_podman_runtime() && container_utils::get_runtime_version() >= (4, 1)
        {
            security_args.push("--userns".to_string());
            security_args.push("nomap".to_string());
        }

        let seccomp_json_path = container_utils::make_seccomp_json_accessible();
        security_args.push("--security-opt".to_string());
        security_args.push(format!("seccomp={}", seccomp_json_path.display()));

        security_args.push("--cap-drop".to_string());
        security_args.push("all".to_string());
        security_args.push("--cap-add".to_string());
        security_args.push("SYS_CHROOT".to_string());
        security_args.push("--security-opt".to_string());
        security_args.push("label=type:container_engine_t".to_string());

        security_args.push("--network=none".to_string());
        security_args.push("-u".to_string());
        security_args.push("dangerzone".to_string());

        security_args
    }

    /// Unique container name for the doc-to-pixels phase.
    fn doc_to_pixels_container_name(&self, document: &Document) -> String {
        format!(
            "{}doc-to-pixels-{}",
            container_utils::CONTAINER_PREFIX,
            document.id()
        )
    }

    /// Runs a command inside a disposable container.
    ///
    /// Corresponds to `exec_container`.
    fn exec_container(
        &self,
        command: Vec<String>,
        name: &str,
    ) -> Result<ConversionProcess, ConvertError> {
        let container_name = container_utils::expected_image_name();
        let image_digest = container_utils::get_local_image_digest(None)?;
        if !bypass_signature_checks() {
            verify_local_image(&image_digest)?;
        }

        let mut args: Vec<String> = vec!["run".to_string()];
        args.extend(Self::get_runtime_security_args());
        if self.debug {
            args.push("-e".to_string());
            args.push("RUNSC_DEBUG=1".to_string());
        }
        args.push("--rm".to_string());
        args.push("-i".to_string());
        args.push("--name".to_string());
        args.push(name.to_string());
        args.push(format!("{container_name}@sha256:{image_digest}"));
        args.extend(command);

        let podman = container_utils::init_podman_command();
        let spawn = SpawnOptions {
            stdin: Stdio::piped(),
            stdout: Stdio::piped(),
            stderr: if self.should_capture_stderr() {
                Stdio::piped()
            } else {
                Stdio::null()
            },
            new_session: true,
        };
        podman
            .run_spawned(&args, spawn)
            .map_err(ConvertError::Podman)
    }
}

impl IsolationProvider for Container {
    fn requires_install(&self) -> bool {
        true
    }

    fn start_doc_to_pixels_proc(
        &self,
        document: &Document,
        ocr_lang: Option<&str>,
    ) -> Result<ConversionProcess, ConvertError> {
        // Convert the document to pixels. The binary is the Rust sandbox
        // converter, installed by the container image into /opt/dangerzone.
        // When OCR is requested, the language is forwarded so the sandbox can
        // run Tesseract and return searchable PDF pages.
        let mut command = vec!["/opt/dangerzone/dz-convert".to_string()];
        if let Some(ocr_lang) = ocr_lang {
            command.push("--ocr-lang".to_string());
            command.push(ocr_lang.to_string());
        }
        let name = self.doc_to_pixels_container_name(document);
        self.exec_container(command, &name)
    }

    fn terminate_doc_to_pixels_proc(&self, document: &Document, p: &mut ConversionProcess) {
        // There are two steps to gracefully terminate a conversion process:
        // 1. Kill the container, and check that it has exited.
        // 2. Gracefully terminate the conversion process, in case it's stuck
        //    on I/O.
        //
        // We choose to terminate spawned containers using first the `kill`
        // action that the container runtime provides, instead of terminating
        // the process that spawned them. The reason is that this process is
        // not always tied to the underlying container. For instance, in Docker
        // containers, this process is actually connected to the Docker daemon,
        // and killing it will just close the associated standard streams.
        if let Err(error) =
            container_utils::kill_container(&self.doc_to_pixels_container_name(document))
        {
            log::debug!("Could not kill container: {error}");
        }
        terminate_process_group(p);
    }

    fn ensure_stop_doc_to_pixels_proc(
        &self,
        document: &Document,
        p: &mut ConversionProcess,
        timeout_grace: u64,
        timeout_force: u64,
    ) {
        crate::base::ensure_stop_common(self, document, p, timeout_grace, timeout_force);

        // Check if the container no longer exists, either because we
        // successfully killed it, or because it exited on its own. We operate
        // under the assumption that after a podman kill / docker kill
        // invocation, this will likely be the case, else the container runtime
        // has experienced a problem, and we should report it.
        let podman = container_utils::init_podman_command();
        let name = self.doc_to_pixels_container_name(document);
        let ps_args = vec!["ps".to_string(), "-a".to_string()];
        match podman.run_captured(&ps_args, true) {
            Ok(all_containers) => {
                if all_containers.contains(&name) {
                    log::warn!("Container '{name}' did not stop gracefully");
                }
            }
            Err(CommandError(_)) => {
                // FIXME: This fallback should be removed once we drop support
                // for Ubuntu 22.04. It's there because `podman ps -a` somehow
                // fails on Ubuntu 22.04, probably due to a bug. For more info,
                // see https://github.com/freedomofpress/dangerzone/issues/1294
                log::warn!(
                    "Could not list containers because 'podman ps -a' failed.\n\
                     Container '{name}' may still be running..."
                );
            }
        }
    }

    fn get_max_parallel_conversions(&self) -> usize {
        // FIXME: hardcoded 1 until long conversions are better handled.
        // https://github.com/freedomofpress/dangerzone/issues/257
        1
    }

    fn debug(&self) -> bool {
        self.debug
    }
}
